# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PRINCIPLES OF MACHINE LEARNING BOOK
author: Jesus Requena Carrion
logo: ./images/qmul_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # off : to stop execution of cells during creating document
  # force : to execute the cells
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: principles_machine_learning.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ammaryasirnaich/MachinelearningBook       # Online location of your book
  path_to_book: Principles_of_machine_learning  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"




